* Documentation
  This repository is my collection of elisp packages from all over the
  Internet, and also a collection of my own code, all mixed together.
  It is not well organized.

** make-tags-file.el
*** TODO find-top-level isn't working correctly, at least on windows.

* Notes & Cheat Sheets
** IRC
*** Change Nickname
    - =/query NickServ=
    - =ghost= if I'm still connected.
    - =id= if I'm not authenticated.
    - =/nick= to change.

** Git
*** Search history.
    : git log -S'pattern'

** goto-last-change.el
   =C-x C-\= visit the list of recent points.

** MozREPL
*** Flush the cache from anywhere.
    : repl._creationContext.webdeveloper_clearCache()

*** Enter the page context.
    : repl.enter(content)

** Windows Hacks & Workarounds
*** Installing Windows Fonts
    Copy =*.ttf= to Control Panel -> Fonts using explorer. In emacs,
    they're referred to by the pretty name in the Fonts panel with an
    appended point size.

*** IE Registry
    =\HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main=.
    =Friendly http errors=, =Disable Script Debugger=, and
    =DisableScriptDebuggerIE=.

*** Fullscreen Emacs
    From #emacs:

#+BEGIN_SRC
<nimred> wich way can i maximize emacs windows using MS Windows ?       [13:58]
<proq> nimred: add to your .emacs:  (add-to-list 'default-frame-alist '(height
       . 105))    (add-to-list 'default-frame-alist '(width . 229))     [14:00]
<proq> you will need to adjust the numbers 105 and 229 though
#+END_SRC
